// AUTO-GENERATED by tools/sync/generate-config-types.ts
// Source: config/*.yaml

export interface ClimateSchemaParams {
    lapse_rate_c_per_km: number;
    height_to_meters: number;
    precip_min_mm: number;
    precip_max_mm: number;
    hadley_anomaly_gain: number;
    distance_scale_km: number;
    continentality_gain: number;
    moisture_convergence_gain: number;
    convergence_min_mm: number;
    convergence_max_mm: number;
    convergence_blend: number;
    precip_cap_from_moisture: number;
    hotspot_precip_gain_mm: number;
    hotspot_coast_distance_km: number;
    hotspot_fetch_weight: number;
    hotspot_convergence_weight: number;
    orographic_uplift_gain_mm: number;
    orographic_rise_scale_m: number;
    orographic_trace_steps: number;
    orographic_trace_alignment_min: number;
    orographic_step_decay: number;
    rain_shadow_gain: number;
    rain_shadow_scale_m: number;
    rain_shadow_distance_km: number;
    downwind_depletion_gain: number;
    downwind_depletion_max: number;
    downwind_depletion_steps: number;
    downwind_depletion_passes: number;
    downwind_depletion_decay: number;
    downwind_alignment_min: number;
    cold_coast_gain: number;
    cold_relax_hotspot_weight: number;
    core_substeps: number;
    core_temperature_diffusion_gain: number;
    core_moisture_transport_gain: number;
    core_condense_excess_gain: number;
    core_orographic_condense_gain: number;
    core_ocean_evaporation_gain: number;
    core_land_recycle_gain: number;
    core_land_bucket_capacity_mm: number;
    core_land_drainage_gain: number;
    core_land_relaxation_years: number;
    core_humidity_floor_mm: number;
    core_humidity_ref_mm: number;
    core_humidity_cc_rate_per_c: number;
}

export const ClimateSchemaParamsKeys = [
    "lapse_rate_c_per_km",
    "height_to_meters",
    "precip_min_mm",
    "precip_max_mm",
    "hadley_anomaly_gain",
    "distance_scale_km",
    "continentality_gain",
    "moisture_convergence_gain",
    "convergence_min_mm",
    "convergence_max_mm",
    "convergence_blend",
    "precip_cap_from_moisture",
    "hotspot_precip_gain_mm",
    "hotspot_coast_distance_km",
    "hotspot_fetch_weight",
    "hotspot_convergence_weight",
    "orographic_uplift_gain_mm",
    "orographic_rise_scale_m",
    "orographic_trace_steps",
    "orographic_trace_alignment_min",
    "orographic_step_decay",
    "rain_shadow_gain",
    "rain_shadow_scale_m",
    "rain_shadow_distance_km",
    "downwind_depletion_gain",
    "downwind_depletion_max",
    "downwind_depletion_steps",
    "downwind_depletion_passes",
    "downwind_depletion_decay",
    "downwind_alignment_min",
    "cold_coast_gain",
    "cold_relax_hotspot_weight",
    "core_substeps",
    "core_temperature_diffusion_gain",
    "core_moisture_transport_gain",
    "core_condense_excess_gain",
    "core_orographic_condense_gain",
    "core_ocean_evaporation_gain",
    "core_land_recycle_gain",
    "core_land_bucket_capacity_mm",
    "core_land_drainage_gain",
    "core_land_relaxation_years",
    "core_humidity_floor_mm",
    "core_humidity_ref_mm",
    "core_humidity_cc_rate_per_c",
] as const satisfies readonly (keyof ClimateSchemaParams)[];

export interface DomesticatesSchemaParams {
    origin_count_limit: number;
    origin_min_region_cells: number;
    origin_seed_strength_crop: number;
    origin_seed_strength_livestock: number;
    max_dt: number;
    moisture_precip_scale_mm: number;
    moisture_aridity_scale: number;
    origin_candidate_cutoff_ratio: number;
    origin_top_candidate_ratio: number;
    diffusion_memory_decay: number;
    diffusion_memory_gain: number;
    diffusion_memory_river_w: number;
    diffusion_memory_height_w: number;
    diffusion_memory_biome_w: number;
}

export const DomesticatesSchemaParamsKeys = [
    "origin_count_limit",
    "origin_min_region_cells",
    "origin_seed_strength_crop",
    "origin_seed_strength_livestock",
    "max_dt",
    "moisture_precip_scale_mm",
    "moisture_aridity_scale",
    "origin_candidate_cutoff_ratio",
    "origin_top_candidate_ratio",
    "diffusion_memory_decay",
    "diffusion_memory_gain",
    "diffusion_memory_river_w",
    "diffusion_memory_height_w",
    "diffusion_memory_biome_w",
] as const satisfies readonly (keyof DomesticatesSchemaParams)[];

export interface GlaciologySchemaParams {
    accum_temp_threshold_c: number;
    ablation_temp_threshold_c: number;
    accumulation_gain: number;
    accumulation_temp_sensitivity: number;
    ablation_gain: number;
    thickness_response_rate: number;
    melt_runoff_gain: number;
    erosion_gain: number;
    glacial_erosion_coupling: number;
    sea_level_coupling: number;
    sea_level_relaxation_tau_ticks: number;
    ice_ocean_coupling_tau_ticks: number;
    environment_spinup_ticks: number;
    mass_conservation_epsilon: number;
    ice_load_to_bedrock_coupling: number;
    isostatic_adjustment_rate: number;
}

export const GlaciologySchemaParamsKeys = [
    "accum_temp_threshold_c",
    "ablation_temp_threshold_c",
    "accumulation_gain",
    "accumulation_temp_sensitivity",
    "ablation_gain",
    "thickness_response_rate",
    "melt_runoff_gain",
    "erosion_gain",
    "glacial_erosion_coupling",
    "sea_level_coupling",
    "sea_level_relaxation_tau_ticks",
    "ice_ocean_coupling_tau_ticks",
    "environment_spinup_ticks",
    "mass_conservation_epsilon",
    "ice_load_to_bedrock_coupling",
    "isostatic_adjustment_rate",
] as const satisfies readonly (keyof GlaciologySchemaParams)[];

export interface RuntimeSchemaParams {
    activity_signal_gain_terrain: number;
    activity_signal_gain_river: number;
    activity_signal_gain_climate: number;
    activity_signal_gain_ecology: number;
    activity_signal_gain_civilization: number;
    activity_step_baseline_terrain: number;
    activity_step_baseline_river: number;
    activity_step_baseline_climate: number;
    activity_step_baseline_ecology: number;
    activity_step_baseline_civilization: number;
    activity_weight_mix: number;
    activity_queue_pressure_gain: number;
}

export const RuntimeSchemaParamsKeys = [
    "activity_signal_gain_terrain",
    "activity_signal_gain_river",
    "activity_signal_gain_climate",
    "activity_signal_gain_ecology",
    "activity_signal_gain_civilization",
    "activity_step_baseline_terrain",
    "activity_step_baseline_river",
    "activity_step_baseline_climate",
    "activity_step_baseline_ecology",
    "activity_step_baseline_civilization",
    "activity_weight_mix",
    "activity_queue_pressure_gain",
] as const satisfies readonly (keyof RuntimeSchemaParams)[];

export interface TerrainSchemaParams {
    level: number;
    harmonic_max_l: number;
    spectral_alpha: number;
    plate_count_min: number;
    plate_count_max: number;
    ocean_plate_ratio: number;
    boundary_band: number;
    boundary_convergent_base_gain: number;
    boundary_divergent_base_gain: number;
    boundary_transform_relief_gain: number;
    trench_gain: number;
    arc_gain: number;
    collision_gain: number;
    rift_gain: number;
    boundary_trench_width: number;
    boundary_arc_width: number;
    boundary_collision_width: number;
    boundary_rift_width: number;
    boundary_obliquity_mix: number;
    boundary_distance_falloff: number;
    boundary_anisotropy: number;
    rollback_gain: number;
    rollback_suppression: number;
    rollback_fraction_max: number;
    rollback_threshold: number;
    backarc_tension_gain: number;
    dip_density_scale: number;
    subduction_depth_gain: number;
    convergence_memory_rate: number;
    convergence_memory_spatial_smooth: number;
    arc_volcanism_gain: number;
    ridge_volcanism_gain: number;
    hotspot_volcanism_gain: number;
    backarc_volcanism_gain: number;
    volcanic_uplift_gain: number;
    volcanic_thickening_gain: number;
    river_rain_base: number;
    river_accumulation_threshold: number;
    sink_local_rebuild_radius: number;
    sink_full_rebuild_interval_ticks: number;
    sink_full_rebuild_changed_ratio: number;
    sink_incremental_neighbor_hops: number;
    sink_overflow_hysteresis: number;
    sink_min_capacity: number;
    erosion_iterations: number;
    hydraulic_erosion_rate: number;
    hydraulic_deposit_rate: number;
    sediment_capacity_gain: number;
    erosion_min_slope: number;
    erosion_max_delta_per_iter: number;
    coastal_deposit_rate: number;
    shallow_sea_floor: number;
    river_inertia_gain: number;
    river_curvature_penalty: number;
    baseflow_infiltration_rate: number;
    baseflow_release_rate: number;
    baseflow_storage_cap: number;
    continent_competence_noise_gain: number;
    continent_competence_large_scale: number;
    continent_competence_mid_scale: number;
    continent_competence_weight_gain: number;
    continent_foldability_from_competence: number;
    continent_erodibility_from_competence: number;
    mantle_density: number;
    continental_crust_density: number;
    oceanic_base_density: number;
    age_density_gain: number;
    erosion_thickness_coupling: number;
    deposition_thickness_coupling: number;
    tectonic_uplift_gain: number;
    plate_motion_gain: number;
    boundary_reclassify_interval: number;
    river_rebuild_interval_min: number;
    river_rebuild_interval_max: number;
    river_activity_high_threshold: number;
    river_activity_low_threshold: number;
    tectonic_subsidence_gain: number;
    thermal_subsidence_gain: number;
    stress_relaxation_rate: number;
    isostatic_adjustment_rate: number;
    subduction_age_coupling: number;
    subduction_initiation_threshold: number;
    subduction_density_threshold: number;
    hypsometry_land_p50: number;
    hypsometry_land_p90: number;
    hypsometry_ocean_p50: number;
    hypsometry_ocean_p90: number;
    mantle_heat_input: number;
    mantle_heat_loss: number;
    mantle_diffusion_rate: number;
    plume_threshold: number;
    plume_gain: number;
    plume_heat_release_rate: number;
    uplift_saturation_soft: number;
    uplift_saturation_hard: number;
    age_advection_gain: number;
    nonlinear_diffusion_gain: number;
    isostatic_relax_gain: number;
    age_ref: number;
}

export const TerrainSchemaParamsKeys = [
    "level",
    "harmonic_max_l",
    "spectral_alpha",
    "plate_count_min",
    "plate_count_max",
    "ocean_plate_ratio",
    "boundary_band",
    "boundary_convergent_base_gain",
    "boundary_divergent_base_gain",
    "boundary_transform_relief_gain",
    "trench_gain",
    "arc_gain",
    "collision_gain",
    "rift_gain",
    "boundary_trench_width",
    "boundary_arc_width",
    "boundary_collision_width",
    "boundary_rift_width",
    "boundary_obliquity_mix",
    "boundary_distance_falloff",
    "boundary_anisotropy",
    "rollback_gain",
    "rollback_suppression",
    "rollback_fraction_max",
    "rollback_threshold",
    "backarc_tension_gain",
    "dip_density_scale",
    "subduction_depth_gain",
    "convergence_memory_rate",
    "convergence_memory_spatial_smooth",
    "arc_volcanism_gain",
    "ridge_volcanism_gain",
    "hotspot_volcanism_gain",
    "backarc_volcanism_gain",
    "volcanic_uplift_gain",
    "volcanic_thickening_gain",
    "river_rain_base",
    "river_accumulation_threshold",
    "sink_local_rebuild_radius",
    "sink_full_rebuild_interval_ticks",
    "sink_full_rebuild_changed_ratio",
    "sink_incremental_neighbor_hops",
    "sink_overflow_hysteresis",
    "sink_min_capacity",
    "erosion_iterations",
    "hydraulic_erosion_rate",
    "hydraulic_deposit_rate",
    "sediment_capacity_gain",
    "erosion_min_slope",
    "erosion_max_delta_per_iter",
    "coastal_deposit_rate",
    "shallow_sea_floor",
    "river_inertia_gain",
    "river_curvature_penalty",
    "baseflow_infiltration_rate",
    "baseflow_release_rate",
    "baseflow_storage_cap",
    "continent_competence_noise_gain",
    "continent_competence_large_scale",
    "continent_competence_mid_scale",
    "continent_competence_weight_gain",
    "continent_foldability_from_competence",
    "continent_erodibility_from_competence",
    "mantle_density",
    "continental_crust_density",
    "oceanic_base_density",
    "age_density_gain",
    "erosion_thickness_coupling",
    "deposition_thickness_coupling",
    "tectonic_uplift_gain",
    "plate_motion_gain",
    "boundary_reclassify_interval",
    "river_rebuild_interval_min",
    "river_rebuild_interval_max",
    "river_activity_high_threshold",
    "river_activity_low_threshold",
    "tectonic_subsidence_gain",
    "thermal_subsidence_gain",
    "stress_relaxation_rate",
    "isostatic_adjustment_rate",
    "subduction_age_coupling",
    "subduction_initiation_threshold",
    "subduction_density_threshold",
    "hypsometry_land_p50",
    "hypsometry_land_p90",
    "hypsometry_ocean_p50",
    "hypsometry_ocean_p90",
    "mantle_heat_input",
    "mantle_heat_loss",
    "mantle_diffusion_rate",
    "plume_threshold",
    "plume_gain",
    "plume_heat_release_rate",
    "uplift_saturation_soft",
    "uplift_saturation_hard",
    "age_advection_gain",
    "nonlinear_diffusion_gain",
    "isostatic_relax_gain",
    "age_ref",
] as const satisfies readonly (keyof TerrainSchemaParams)[];

