// AUTO-GENERATED by tools/sync/sync-runtime-params.mjs
// Source: config/runtime.yaml

export const RUNTIME_PARAMS = Object.freeze({
    activity_signal_gain_terrain: 24.0,
    activity_signal_gain_river: 1.0,
    activity_signal_gain_climate: 3.5,
    activity_signal_gain_ecology: 3.5,
    activity_signal_gain_civilization: 1.0,
    activity_step_baseline_terrain: 0.06,
    activity_step_baseline_river: 0.08,
    activity_step_baseline_climate: 0.04,
    activity_step_baseline_ecology: 0.03,
    activity_step_baseline_civilization: 0.02,
    activity_weight_mix: 0.45,
    activity_queue_pressure_gain: 0.35,
});

