#[derive(Clone, Copy, Default)]
pub(super) struct EulerFrontAdvectionMetrics {
    pub(super) substeps: u32,
    pub(super) topology_event_cell_count: u32,
    pub(super) topology_constrained_segment_count: u32,
    pub(super) raw_expected_cell_count: f32,
    pub(super) accumulated_expected_cell_count: f32,
    pub(super) component_budget_cell_count: u32,
    pub(super) transferable_component_budget_cell_count: u32,
    pub(super) plate_consistency_budget_cell_count: u32,
    pub(super) plate_consistency_deferred_cell_count: u32,
    pub(super) plate_consistency_donor_limited_cell_count: u32,
    pub(super) plate_consistency_outgoing_limited_cell_count: u32,
    pub(super) plate_consistency_incoming_limited_cell_count: u32,
    pub(super) plate_consistency_net_area_limited_cell_count: u32,
    pub(super) plate_consistency_max_projected_out_ratio: f32,
    pub(super) actual_transfer_cell_count: u32,
    pub(super) patch_rejected_component_count: u32,
    pub(super) patch_rejected_budget_cell_count: u32,
    pub(super) source_fragment_rejected_component_count: u32,
    pub(super) source_fragment_rejected_budget_cell_count: u32,
    pub(super) target_disconnected_rejected_component_count: u32,
    pub(super) target_disconnected_rejected_budget_cell_count: u32,
}
