[package]
name = "frey_wasm"
version = "0.1.0"
edition = "2021"

[features]
default = ["wasm_transport"]
wasm_transport = ["dep:js-sys", "dep:serde-wasm-bindgen", "dep:wasm-bindgen"]
precompute_server = ["wasm_transport", "dep:axum", "dep:tokio", "dep:tower-http", "dep:zstd"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = { version = "2.0.1", features = ["serde"] }
serde-wasm-bindgen = { version = "0.6", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
smallvec = { version = "1.13", features = ["serde"] }
slotmap = "1.0"
verification_runtime = { path = "crates/verification_runtime" }
axum = { version = "0.7", optional = true }
tokio = { version = "1.42", features = ["macros", "rt-multi-thread", "net"], optional = true }
tower-http = { version = "0.6", features = ["cors"], optional = true }
zstd = { version = "0.13", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
lto = true
opt-level = "s"
strip = "debuginfo"
