import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
    parseSelfDescribingYaml,
    rustLiteral,
    validateParams,
    writeFileIfChanged,
    type TypeHint,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const CONFIG_DIR = path.join(ROOT_DIR, "config");
const WEB_PARAMS_DIR = path.join(ROOT_DIR, "web", "src", "interface", "params");
const RUST_GENERATED_DIR = path.join(ROOT_DIR, "rust", "src", "generated");

interface ParamMapping {
    /** dot-separated YAML path (e.g. "temperature.lapse_rate_c_per_km") */
    yamlPath: string;
    /** Rust/TS field name (e.g. "lapse_rate_c_per_km") */
    fieldName: string;
    type: TypeHint;
    raw: string;
    value: number;
}

/**
 * Extract param mappings from a self-describing YAML file.
 * In flat format, the yamlPath IS the field name.
 */
function extractParams(yamlPath: string): ParamMapping[] {
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseSelfDescribingYaml(yamlText);
    validateParams(parsed);

    const params: ParamMapping[] = [];
    for (const [fieldName, entry] of parsed) {
        params.push({
            yamlPath: fieldName,
            fieldName,
            type: entry.type,
            raw: entry.raw,
            value: entry.value,
        });
    }
    return params;
}

function syncRuntimeParams(): number {
    const yamlFile = path.join(CONFIG_DIR, "runtime.yaml");
    const outPath = path.join(WEB_PARAMS_DIR, "runtime.ts");

    const params = extractParams(yamlFile);

    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    lines.push("// Source: config/runtime.yaml");
    lines.push("");
    lines.push('import type { RuntimeSchemaParams } from "./generated-schema-types";');
    lines.push("");
    lines.push("export const RUNTIME_PARAMS = Object.freeze({");
    for (const param of params) {
        lines.push(`    ${param.fieldName}: ${param.raw},`);
    }
    lines.push("} satisfies RuntimeSchemaParams);");
    lines.push("");

    return Number(writeFileIfChanged(outPath, `${lines.join("\n")}\n`));
}

function syncTerrainParams(): number {
    const yamlFile = path.join(CONFIG_DIR, "terrain.yaml");
    const tsOutPath = path.join(WEB_PARAMS_DIR, "terrain.ts");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "terrain_params_defaults.rs");

    const params = extractParams(yamlFile);

    const tsLines: string[] = [];
    tsLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    tsLines.push("// Source: config/terrain.yaml");
    tsLines.push("");
    tsLines.push('import type { TerrainSchemaParams } from "./generated-schema-types";');
    tsLines.push("");
    tsLines.push("export const TERRAIN_PARAMS = Object.freeze({");
    for (const param of params) {
        tsLines.push(`    ${param.fieldName}: ${param.raw},`);
    }
    tsLines.push("} satisfies TerrainSchemaParams);");
    tsLines.push("");
    tsLines.push("export const TERRAIN_LEVEL = TERRAIN_PARAMS.level;");
    tsLines.push("");

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/terrain.yaml");
    rustLines.push("");
    rustLines.push("use crate::GeologyParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_terrain_params() -> GeologyParams {");
    rustLines.push("    GeologyParams {");
    for (const param of params) {
        rustLines.push(`        ${param.fieldName}: ${rustLiteral(param.raw, param.type)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");

    const tsChanged = Number(writeFileIfChanged(tsOutPath, `${tsLines.join("\n")}\n`));
    const rustChanged = Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
    return tsChanged + rustChanged;
}

function syncClimateParams(): number {
    const yamlFile = path.join(CONFIG_DIR, "climate.yaml");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "climate_params_defaults.rs");

    const params = extractParams(yamlFile);

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/climate.yaml");
    rustLines.push("");
    rustLines.push("use crate::sim::climate::types::ClimateParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_climate_params() -> ClimateParams {");
    rustLines.push("    ClimateParams {");
    for (const param of params) {
        rustLines.push(`        ${param.fieldName}: ${rustLiteral(param.raw, param.type)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");

    return Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
}

function syncDomesticatesParams(): number {
    const yamlFile = path.join(CONFIG_DIR, "domesticates.yaml");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "domesticates_params_defaults.rs");

    const params = extractParams(yamlFile);

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/domesticates.yaml");
    rustLines.push("");
    rustLines.push("use crate::sim::domesticates::types::DomesticatesParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_domesticates_params() -> DomesticatesParams {");
    rustLines.push("    DomesticatesParams {");
    for (const param of params) {
        rustLines.push(`        ${param.fieldName}: ${rustLiteral(param.raw, param.type)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");

    return Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
}

function syncGlaciologyParams(): number {
    const yamlFile = path.join(CONFIG_DIR, "glaciology.yaml");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "glaciology_params_defaults.rs");

    const params = extractParams(yamlFile);

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/glaciology.yaml");
    rustLines.push("");
    rustLines.push("use crate::sim::glaciology::types::GlaciologyParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_glaciology_params() -> GlaciologyParams {");
    rustLines.push("    GlaciologyParams {");
    for (const param of params) {
        rustLines.push(`        ${param.fieldName}: ${rustLiteral(param.raw, param.type)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");

    return Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
}

function runTypesAndDocsStep(scriptPath: string) {
    const result = spawnSync("tsx", [scriptPath], {
        cwd: ROOT_DIR,
        stdio: "inherit",
        shell: process.platform === "win32",
    });
    if (result.status !== 0) {
        throw new Error(`config sync failed: ${scriptPath}`);
    }
}

function main() {
    const runtimeChanged = syncRuntimeParams();
    const terrainChanged = syncTerrainParams();
    const climateChanged = syncClimateParams();
    const domesticatesChanged = syncDomesticatesParams();
    const glaciologyChanged = syncGlaciologyParams();
    runTypesAndDocsStep("tools/sync/generate-config-types.ts");

    const changedTotal =
        runtimeChanged
        + terrainChanged
        + climateChanged
        + domesticatesChanged
        + glaciologyChanged;
    console.log(`config:sync completed (${changedTotal} config file(s) updated before docs/types)`);
}

main();
