import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
    jsLiteral,
    loadSchemaFromJson,
    parseYamlNumericScalars,
    rustLiteral,
    validateAgainstSchema,
    writeFileIfChanged,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const CONFIG_DIR = path.join(ROOT_DIR, "config");
const SCHEMA_DIR = path.join(CONFIG_DIR, "schema");
const WEB_PARAMS_DIR = path.join(ROOT_DIR, "web", "src", "interface", "params");
const RUST_GENERATED_DIR = path.join(ROOT_DIR, "rust", "src", "generated");

function syncRuntimeParams(): number {
    const yamlPath = path.join(CONFIG_DIR, "runtime.yaml");
    const schemaPath = path.join(SCHEMA_DIR, "runtime.schema.json");
    const outPath = path.join(WEB_PARAMS_DIR, "runtime.ts");

    const schema: SchemaEntry[] = loadSchemaFromJson(schemaPath);
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    lines.push("// Source: config/runtime.yaml");
    lines.push("");
    lines.push('import type { RuntimeSchemaParams } from "./generated-schema-types";');
    lines.push("");
    lines.push("export const RUNTIME_PARAMS = Object.freeze({");
    for (const [pathKey, outKey] of schema) {
        lines.push(`    ${outKey}: ${jsLiteral(parsed.get(pathKey)!.raw)},`);
    }
    lines.push("} satisfies RuntimeSchemaParams);");
    lines.push("");

    return Number(writeFileIfChanged(outPath, `${lines.join("\n")}\n`));
}

function syncTerrainParams(): number {
    const yamlPath = path.join(CONFIG_DIR, "terrain.yaml");
    const schemaPath = path.join(SCHEMA_DIR, "terrain.schema.json");
    const tsOutPath = path.join(WEB_PARAMS_DIR, "terrain.ts");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "terrain_params_defaults.rs");

    const schema: SchemaEntry[] = loadSchemaFromJson(schemaPath);
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const tsLines: string[] = [];
    tsLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    tsLines.push("// Source: config/terrain.yaml");
    tsLines.push("");
    tsLines.push('import type { TerrainSchemaParams } from "./generated-schema-types";');
    tsLines.push("");
    tsLines.push("export const TERRAIN_PARAMS = Object.freeze({");
    for (const [pathKey, outKey] of schema) {
        tsLines.push(`    ${outKey}: ${jsLiteral(parsed.get(pathKey)!.raw)},`);
    }
    tsLines.push("} satisfies TerrainSchemaParams);");
    tsLines.push("");
    tsLines.push("export const TERRAIN_LEVEL = TERRAIN_PARAMS.level;");
    tsLines.push("");

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/terrain.yaml");
    rustLines.push("");
    rustLines.push("use crate::GeologyParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_terrain_params() -> GeologyParams {");
    rustLines.push("    GeologyParams {");
    for (const [pathKey, outKey, typeHint] of schema) {
        rustLines.push(`        ${outKey}: ${rustLiteral(parsed.get(pathKey)!.raw, typeHint)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");
    rustLines.push("");

    const tsChanged = Number(writeFileIfChanged(tsOutPath, `${tsLines.join("\n")}\n`));
    const rustChanged = Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
    return tsChanged + rustChanged;
}

function syncClimateParams(): number {
    const yamlPath = path.join(CONFIG_DIR, "climate.yaml");
    const schemaPath = path.join(SCHEMA_DIR, "climate.schema.json");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "climate_params_defaults.rs");

    const schema: SchemaEntry[] = loadSchemaFromJson(schemaPath);
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/climate.yaml");
    rustLines.push("");
    rustLines.push("use crate::sim::climate::types::ClimateParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_climate_params() -> ClimateParams {");
    rustLines.push("    ClimateParams {");
    for (const [pathKey, outKey, typeHint] of schema) {
        rustLines.push(`        ${outKey}: ${rustLiteral(parsed.get(pathKey)!.raw, typeHint)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");
    rustLines.push("");

    return Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
}

function syncGlaciologyParams(): number {
    const yamlPath = path.join(CONFIG_DIR, "glaciology.yaml");
    const schemaPath = path.join(SCHEMA_DIR, "glaciology.schema.json");
    const rustOutPath = path.join(RUST_GENERATED_DIR, "glaciology_params_defaults.rs");

    const schema: SchemaEntry[] = loadSchemaFromJson(schemaPath);
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const rustLines: string[] = [];
    rustLines.push("// AUTO-GENERATED by tools/sync/config-sync.ts");
    rustLines.push("// Source: config/glaciology.yaml");
    rustLines.push("");
    rustLines.push("use crate::sim::glaciology::types::GlaciologyParams;");
    rustLines.push("");
    rustLines.push("pub(crate) fn build_default_glaciology_params() -> GlaciologyParams {");
    rustLines.push("    GlaciologyParams {");
    for (const [pathKey, outKey, typeHint] of schema) {
        rustLines.push(`        ${outKey}: ${rustLiteral(parsed.get(pathKey)!.raw, typeHint)},`);
    }
    rustLines.push("    }");
    rustLines.push("}");
    rustLines.push("");

    return Number(writeFileIfChanged(rustOutPath, `${rustLines.join("\n")}\n`));
}

function runTypesAndDocsStep(scriptPath: string) {
    const result = spawnSync("tsx", [scriptPath], {
        cwd: ROOT_DIR,
        stdio: "inherit",
        shell: process.platform === "win32",
    });
    if (result.status !== 0) {
        throw new Error(`config sync failed: ${scriptPath}`);
    }
}

function main() {
    const runtimeChanged = syncRuntimeParams();
    const terrainChanged = syncTerrainParams();
    const climateChanged = syncClimateParams();
    const glaciologyChanged = syncGlaciologyParams();
    runTypesAndDocsStep("tools/sync/generate-config-types.ts");
    runTypesAndDocsStep("tools/sync/generate-config-docs.ts");

    const changedTotal = runtimeChanged + terrainChanged + climateChanged + glaciologyChanged;
    console.log(`config:sync completed (${changedTotal} config file(s) updated before docs/types)`);
}

main();
