import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { writeFileIfChanged, type SchemaEntry } from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const SCHEMA_DIR = path.join(ROOT_DIR, "config", "schema");
const OUT_PATH = path.join(ROOT_DIR, "docs", "architecture", "config-schema.md");

function readSchema(fileName: string): SchemaEntry[] {
    const schemaPath = path.join(SCHEMA_DIR, fileName);
    const parsed = JSON.parse(fs.readFileSync(schemaPath, "utf8")) as SchemaEntry[];
    return parsed;
}

function buildSection(name: string, schema: SchemaEntry[]): string {
    const lines: string[] = [];
    lines.push(`## ${name}`);
    lines.push("");
    lines.push("| path | output_key | rust_type |");
    lines.push("| --- | --- | --- |");
    for (const [pathKey, outKey, typeHint] of schema) {
        lines.push(`| \`${pathKey}\` | \`${outKey}\` | \`${typeHint ?? "-"}\` |`);
    }
    lines.push("");
    return lines.join("\n");
}

function main() {
    const schemaFiles = fs
        .readdirSync(SCHEMA_DIR)
        .filter((file) => file.endsWith(".schema.json"))
        .sort();
    const sections = schemaFiles.map((file) =>
        buildSection(file.replace(".schema.json", ""), readSchema(file)));

    const content = [
        "# Config Schema",
        "",
        "AUTO-GENERATED by `tools/sync/generate-config-docs.ts`.",
        "Regenerate with `pnpm run config:sync`.",
        "",
        ...sections,
    ].join("\n");

    const changed = writeFileIfChanged(OUT_PATH, `${content}\n`);
    console.log(`config schema docs generated (${Number(changed)} file(s) updated)`);
}

main();
