import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadSchemaFromJson, writeFileIfChanged, type SchemaEntry } from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const SCHEMA_DIR = path.join(ROOT_DIR, "config", "schema");
const TS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "generated-schema-types.ts");
const RUST_OUT_PATH = path.join(ROOT_DIR, "rust", "src", "generated", "config_schema_types.rs");

type SchemaFile = {
    schemaName: string;
    typeName: string;
    entries: SchemaEntry[];
};

function toPascalCase(value: string): string {
    return value
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
}

function readSchemaFiles(): SchemaFile[] {
    const files = fs
        .readdirSync(SCHEMA_DIR)
        .filter((name) => name.endsWith(".schema.json"))
        .sort();
    return files.map((name) => {
        const schemaName = name.replace(/\.schema\.json$/, "");
        const typeName = `${toPascalCase(schemaName)}SchemaParams`;
        const schemaPath = path.join(SCHEMA_DIR, name);
        return {
            schemaName,
            typeName,
            entries: loadSchemaFromJson(schemaPath),
        };
    });
}

function tsNumberType(typeHint?: string): string {
    if (typeHint === "u32") {
        return "number";
    }
    return "number";
}

function rustType(typeHint?: string): string {
    if (typeHint === "u32") {
        return "u32";
    }
    return "f32";
}

function buildTsModule(schemas: SchemaFile[]): string {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/generate-config-types.ts");
    lines.push("// Source: config/schema/*.schema.json");
    lines.push("");
    for (const schema of schemas) {
        lines.push(`export interface ${schema.typeName} {`);
        for (const [, outKey, typeHint] of schema.entries) {
            lines.push(`    ${outKey}: ${tsNumberType(typeHint)};`);
        }
        lines.push("}");
        lines.push("");
        lines.push(`export const ${schema.typeName}Keys = [`);
        for (const [, outKey] of schema.entries) {
            lines.push(`    "${outKey}",`);
        }
        lines.push(`] as const satisfies readonly (keyof ${schema.typeName})[];`);
        lines.push("");
    }
    return `${lines.join("\n")}\n`;
}

function buildRustModule(schemas: SchemaFile[]): string {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/generate-config-types.ts");
    lines.push("// Source: config/schema/*.schema.json");
    lines.push("");
    lines.push("use serde::{Deserialize, Serialize};");
    lines.push("");
    for (const schema of schemas) {
        lines.push("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
        lines.push(`pub struct ${schema.typeName} {`);
        for (const [, outKey, typeHint] of schema.entries) {
            lines.push(`    pub ${outKey}: ${rustType(typeHint)},`);
        }
        lines.push("}");
        lines.push("");
        lines.push(`pub const ${schema.typeName.toUpperCase()}_KEYS: &[&str] = &[`);
        for (const [, outKey] of schema.entries) {
            lines.push(`    "${outKey}",`);
        }
        lines.push("];");
        lines.push("");
    }
    return `${lines.join("\n")}\n`;
}

function main() {
    const schemas = readSchemaFiles();
    const tsChanged = writeFileIfChanged(TS_OUT_PATH, buildTsModule(schemas));
    const rustChanged = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(schemas));
    const changedCount = Number(tsChanged) + Number(rustChanged);
    console.log(`config schema types generated (${changedCount} file(s) updated)`);
}

main();
