import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    parseSelfDescribingYaml,
    validateParams,
    writeFileIfChanged,
    type ParamEntry,
    type TypeHint,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const CONFIG_DIR = path.join(ROOT_DIR, "config");
const TS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "generated-schema-types.ts");
const RUST_OUT_PATH = path.join(ROOT_DIR, "rust", "src", "generated", "config_schema_types.rs");

type SchemaFile = {
    schemaName: string;
    typeName: string;
    entries: ParamEntry[];
};

function toPascalCase(value: string): string {
    return value
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
}

function readSchemaFromYaml(yamlName: string): SchemaFile {
    const yamlPath = path.join(CONFIG_DIR, yamlName);
    const yamlText = fs.readFileSync(yamlPath, "utf8");
    const parsed = parseSelfDescribingYaml(yamlText);
    validateParams(parsed);

    const entries: ParamEntry[] = [];
    for (const [_fieldName, entry] of parsed) {
        entries.push({
            yamlPath: entry.yamlPath,
            fieldName: entry.fieldName,
            type: entry.type,
            value: entry.value,
            raw: entry.raw,
        });
    }

    const schemaName = yamlName.replace(/\.yaml$/, "");
    const typeName = `${toPascalCase(schemaName)}SchemaParams`;
    return { schemaName, typeName, entries };
}

function readAllSchemas(): SchemaFile[] {
    const files = fs
        .readdirSync(CONFIG_DIR)
        .filter((name) => name.endsWith(".yaml"))
        .sort();
    return files.map((name) => readSchemaFromYaml(name));
}

function rustType(typeHint: TypeHint): string {
    return typeHint;
}

function buildTsModule(schemas: SchemaFile[]): string {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/generate-config-types.ts");
    lines.push("// Source: config/*.yaml");
    lines.push("");
    for (const schema of schemas) {
        lines.push(`export interface ${schema.typeName} {`);
        for (const entry of schema.entries) {
            lines.push(`    ${entry.fieldName}: number;`);
        }
        lines.push("}");
        lines.push("");
        lines.push(`export const ${schema.typeName}Keys = [`);
        for (const entry of schema.entries) {
            lines.push(`    "${entry.fieldName}",`);
        }
        lines.push(`] as const satisfies readonly (keyof ${schema.typeName})[];`);
        lines.push("");
    }
    return `${lines.join("\n")}\n`;
}

function buildRustModule(schemas: SchemaFile[]): string {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/generate-config-types.ts");
    lines.push("// Source: config/*.yaml");
    lines.push("");
    lines.push("use serde::{Deserialize, Serialize};");
    lines.push("");
    for (const schema of schemas) {
        lines.push("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]");
        lines.push(`pub struct ${schema.typeName} {`);
        for (const entry of schema.entries) {
            lines.push(`    pub ${entry.fieldName}: ${rustType(entry.type)},`);
        }
        lines.push("}");
        lines.push("");
        lines.push(`pub const ${schema.typeName.toUpperCase()}_KEYS: &[&str] = &[`);
        for (const entry of schema.entries) {
            lines.push(`    "${entry.fieldName}",`);
        }
        lines.push("];");
        lines.push("");
    }
    return `${lines.join("\n")}\n`;
}

function main() {
    const schemas = readAllSchemas();
    const tsChanged = writeFileIfChanged(TS_OUT_PATH, buildTsModule(schemas));
    const rustChanged = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(schemas));
    const changedCount = Number(tsChanged) + Number(rustChanged);
    console.log(`config schema types generated (${changedCount} file(s) updated)`);
}

main();
