import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    parseYamlNumericScalars,
    validateAgainstSchema,
    writeFileIfChanged,
    jsLiteral,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "runtime.yaml");
const JS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "runtime.js");

const SCHEMA: SchemaEntry[] = [
    ["activity.signal_gain.terrain", "activity_signal_gain_terrain"],
    ["activity.signal_gain.river", "activity_signal_gain_river"],
    ["activity.signal_gain.climate", "activity_signal_gain_climate"],
    ["activity.signal_gain.ecology", "activity_signal_gain_ecology"],
    ["activity.signal_gain.civilization", "activity_signal_gain_civilization"],
    ["activity.step_baseline.terrain", "activity_step_baseline_terrain"],
    ["activity.step_baseline.river", "activity_step_baseline_river"],
    ["activity.step_baseline.climate", "activity_step_baseline_climate"],
    ["activity.step_baseline.ecology", "activity_step_baseline_ecology"],
    ["activity.step_baseline.civilization", "activity_step_baseline_civilization"],
    ["activity.weight_mix", "activity_weight_mix"],
    ["activity.queue_pressure_gain", "activity_queue_pressure_gain"],
];

function buildJsModule(parsed: Map<string, { raw: string; value: number }>) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-runtime-params.mjs");
    lines.push("// Source: config/runtime.yaml");
    lines.push("");
    lines.push("export const RUNTIME_PARAMS = Object.freeze({");

    for (const [pathKey, outKey] of SCHEMA) {
        lines.push(`    ${outKey}: ${jsLiteral(parsed.get(pathKey)!.raw)},`);
    }

    lines.push("});");
    return `${lines.join("\n")}\n`;
}

function main() {
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, SCHEMA);

    const jsChanged = writeFileIfChanged(JS_OUT_PATH, buildJsModule(parsed));
    const changedCount = Number(jsChanged);
    console.log(
        `runtime params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${changedCount} file(s) updated)`,
    );
}

main();
