import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    parseYamlNumericScalars,
    validateAgainstSchema,
    writeFileIfChanged,
    rustLiteral,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "climate.yaml");
const RUST_OUT_PATH = path.join(ROOT_DIR, "rust", "src", "generated", "climate_params_defaults.rs");

const SCHEMA: SchemaEntry[] = [
    ["temperature.lapse_rate_c_per_km", "lapse_rate_c_per_km", "f32"],
    ["temperature.height_to_meters", "height_to_meters", "f32"],
    ["precipitation.min_mm", "precip_min_mm", "f32"],
    ["precipitation.max_mm", "precip_max_mm", "f32"],
    ["precipitation.hadley_anomaly_gain", "hadley_anomaly_gain", "f32"],
    ["precipitation.distance_scale_km", "distance_scale_km", "f32"],
    ["precipitation.continentality_gain", "continentality_gain", "f32"],
    ["precipitation.moisture_convergence_gain", "moisture_convergence_gain", "f32"],
    ["precipitation.convergence_min_mm", "convergence_min_mm", "f32"],
    ["precipitation.convergence_max_mm", "convergence_max_mm", "f32"],
    ["precipitation.convergence_blend", "convergence_blend", "f32"],
    ["orography.uplift_gain_mm", "orographic_uplift_gain_mm", "f32"],
    ["orography.rise_scale_m", "orographic_rise_scale_m", "f32"],
    ["orography.trace_steps", "orographic_trace_steps", "u32"],
    ["orography.trace_alignment_min", "orographic_trace_alignment_min", "f32"],
    ["orography.step_decay", "orographic_step_decay", "f32"],
    ["orography.rain_shadow_gain", "rain_shadow_gain", "f32"],
    ["orography.rain_shadow_scale_m", "rain_shadow_scale_m", "f32"],
    ["orography.rain_shadow_distance_km", "rain_shadow_distance_km", "f32"],
    ["orography.downwind_depletion_gain", "downwind_depletion_gain", "f32"],
    ["orography.downwind_depletion_max", "downwind_depletion_max", "f32"],
    ["orography.downwind_depletion_steps", "downwind_depletion_steps", "u32"],
    ["orography.downwind_depletion_passes", "downwind_depletion_passes", "u32"],
    ["orography.downwind_depletion_decay", "downwind_depletion_decay", "f32"],
    ["orography.downwind_alignment_min", "downwind_alignment_min", "f32"],
    ["precipitation.cap_from_moisture", "precip_cap_from_moisture", "f32"],
    ["coastal.cold_coast_gain", "cold_coast_gain", "f32"],
    ["coastal.cold_relax_hotspot_weight", "cold_relax_hotspot_weight", "f32"],
    ["precipitation.hotspot_precip_gain_mm", "hotspot_precip_gain_mm", "f32"],
    ["precipitation.hotspot_coast_distance_km", "hotspot_coast_distance_km", "f32"],
    ["precipitation.hotspot_fetch_weight", "hotspot_fetch_weight", "f32"],
    ["precipitation.hotspot_convergence_weight", "hotspot_convergence_weight", "f32"],
    ["core.substeps", "core_substeps", "u32"],
    ["core.temperature_diffusion_gain", "core_temperature_diffusion_gain", "f32"],
    ["core.moisture_transport_gain", "core_moisture_transport_gain", "f32"],
    ["core.condense_excess_gain", "core_condense_excess_gain", "f32"],
    ["core.orographic_condense_gain", "core_orographic_condense_gain", "f32"],
    ["core.ocean_evaporation_gain", "core_ocean_evaporation_gain", "f32"],
    ["core.land_recycle_gain", "core_land_recycle_gain", "f32"],
    ["core.land_bucket_capacity_mm", "core_land_bucket_capacity_mm", "f32"],
    ["core.land_drainage_gain", "core_land_drainage_gain", "f32"],
    ["core.land_relaxation_years", "core_land_relaxation_years", "f32"],
    ["core.humidity_floor_mm", "core_humidity_floor_mm", "f32"],
    ["core.humidity_ref_mm", "core_humidity_ref_mm", "f32"],
    ["core.humidity_cc_rate_per_c", "core_humidity_cc_rate_per_c", "f32"],
];

function buildRustModule(parsed: Map<string, { raw: string; value: number }>) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-climate-params.mjs");
    lines.push("// Source: config/climate.yaml");
    lines.push("");
    lines.push("use crate::sim::climate::types::ClimateParams;");
    lines.push("");
    lines.push("pub(crate) fn build_default_climate_params() -> ClimateParams {");
    lines.push("    ClimateParams {");

    for (const [pathKey, outKey, typeHint] of SCHEMA) {
        const raw = parsed.get(pathKey)!.raw;
        lines.push(`        ${outKey}: ${rustLiteral(raw, typeHint)},`);
    }

    lines.push("    }");
    lines.push("}");
    return `${lines.join("\n")}\n`;
}

function main() {
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, SCHEMA);

    const changed = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(parsed));
    console.log(
        `climate params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${Number(changed)} file(s) updated)`,
    );
}

main();
