import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    loadSchemaFromJson,
    parseYamlNumericScalars,
    validateAgainstSchema,
    writeFileIfChanged,
    rustLiteral,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "climate.yaml");
const SCHEMA_PATH = path.join(ROOT_DIR, "config", "schema", "climate.schema.json");
const RUST_OUT_PATH = path.join(ROOT_DIR, "rust", "src", "generated", "climate_params_defaults.rs");

function buildRustModule(parsed: Map<string, { raw: string; value: number }>, schema: SchemaEntry[]) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-climate-params.mjs");
    lines.push("// Source: config/climate.yaml");
    lines.push("");
    lines.push("use crate::sim::climate::types::ClimateParams;");
    lines.push("");
    lines.push("pub(crate) fn build_default_climate_params() -> ClimateParams {");
    lines.push("    ClimateParams {");

    for (const [pathKey, outKey, typeHint] of schema) {
        const raw = parsed.get(pathKey)!.raw;
        lines.push(`        ${outKey}: ${rustLiteral(raw, typeHint)},`);
    }

    lines.push("    }");
    lines.push("}");
    return `${lines.join("\n")}\n`;
}

function main() {
    const schema: SchemaEntry[] = loadSchemaFromJson(SCHEMA_PATH);
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const changed = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(parsed, schema));
    console.log(
        `climate params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${Number(changed)} file(s) updated)`,
    );
}

main();
