import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    loadSchemaFromJson,
    parseYamlNumericScalars,
    validateAgainstSchema,
    writeFileIfChanged,
    rustLiteral,
    jsLiteral,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "terrain.yaml");
const SCHEMA_PATH = path.join(ROOT_DIR, "config", "schema", "terrain.schema.json");
const JS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "terrain.js");
const RUST_OUT_PATH = path.join(ROOT_DIR, "rust", "src", "generated", "terrain_params_defaults.rs");

function buildJsModule(parsed: Map<string, { raw: string; value: number }>, schema: SchemaEntry[]) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-terrain-params.mjs");
    lines.push("// Source: config/terrain.yaml");
    lines.push("");
    lines.push("export const TERRAIN_PARAMS = Object.freeze({");

    for (const [pathKey, outKey] of schema) {
        lines.push(`    ${outKey}: ${jsLiteral(parsed.get(pathKey)!.raw)},`);
    }

    lines.push("});");
    lines.push("");
    lines.push("export const TERRAIN_LEVEL = TERRAIN_PARAMS.level;");
    lines.push("");
    return `${lines.join("\n")}\n`;
}

function buildRustModule(parsed: Map<string, { raw: string; value: number }>, schema: SchemaEntry[]) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-terrain-params.mjs");
    lines.push("// Source: config/terrain.yaml");
    lines.push("");
    lines.push("use crate::GeologyParams;");
    lines.push("");
    lines.push("pub(crate) fn build_default_terrain_params() -> GeologyParams {");
    lines.push("    GeologyParams {");

    for (const [pathKey, outKey, typeHint] of schema) {
        lines.push(`        ${outKey}: ${rustLiteral(parsed.get(pathKey)!.raw, typeHint)},`);
    }

    lines.push("    }");
    lines.push("}");
    return `${lines.join("\n")}\n`;
}

function main() {
    const schema: SchemaEntry[] = loadSchemaFromJson(SCHEMA_PATH);
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const jsChanged = writeFileIfChanged(JS_OUT_PATH, buildJsModule(parsed, schema));
    const rustChanged = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(parsed, schema));

    const changedCount = Number(jsChanged) + Number(rustChanged);
    console.log(
        `terrain params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${changedCount} file(s) updated)`,
    );
}

main();
