import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "runtime.yaml");
const JS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "runtime.js");

const SCHEMA = [
    ["activity.signal_gain.terrain", "activity_signal_gain_terrain"],
    ["activity.signal_gain.river", "activity_signal_gain_river"],
    ["activity.signal_gain.climate", "activity_signal_gain_climate"],
    ["activity.signal_gain.ecology", "activity_signal_gain_ecology"],
    ["activity.signal_gain.civilization", "activity_signal_gain_civilization"],
    ["activity.step_baseline.terrain", "activity_step_baseline_terrain"],
    ["activity.step_baseline.river", "activity_step_baseline_river"],
    ["activity.step_baseline.climate", "activity_step_baseline_climate"],
    ["activity.step_baseline.ecology", "activity_step_baseline_ecology"],
    ["activity.step_baseline.civilization", "activity_step_baseline_civilization"],
    ["activity.weight_mix", "activity_weight_mix"],
    ["activity.queue_pressure_gain", "activity_queue_pressure_gain"],
];

function stripInlineComment(value) {
    let inSingle = false;
    let inDouble = false;

    for (let i = 0; i < value.length; i += 1) {
        const ch = value[i];
        if (ch === "'" && !inDouble) {
            inSingle = !inSingle;
            continue;
        }
        if (ch === "\"" && !inSingle) {
            inDouble = !inDouble;
            continue;
        }
        if (ch === "#" && !inSingle && !inDouble) {
            return value.slice(0, i).trim();
        }
    }

    return value.trim();
}

function parseYamlNumericScalars(text) {
    const result = new Map();
    const lines = text.split(/\r?\n/);
    const stack = [];

    lines.forEach((line, index) => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) {
            return;
        }
        if (/\t/.test(line)) {
            throw new Error(`Invalid YAML line ${index + 1}: tab indentation is not supported`);
        }

        const colonIndex = line.indexOf(":");
        if (colonIndex < 0) {
            throw new Error(`Invalid YAML line ${index + 1}: missing ":"`);
        }

        const indent = line.length - line.trimStart().length;
        if (indent % 2 !== 0) {
            throw new Error(`Invalid YAML line ${index + 1}: indentation must use 2-space units`);
        }
        while (stack.length > 0 && indent <= stack[stack.length - 1].indent) {
            stack.pop();
        }

        const localKey = line.slice(0, colonIndex).trim();
        const rawValue = stripInlineComment(line.slice(colonIndex + 1));
        if (!localKey) {
            throw new Error(`Invalid YAML line ${index + 1}: empty key`);
        }

        if (!rawValue) {
            stack.push({ key: localKey, indent });
            return;
        }

        const keyPath = [...stack.map((entry) => entry.key), localKey].join(".");
        if (result.has(keyPath)) {
            throw new Error(`Duplicate key "${keyPath}" at line ${index + 1}`);
        }

        const isNumberLiteral = /^-?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$/.test(rawValue);
        if (!isNumberLiteral) {
            throw new Error(
                `Unsupported value for "${keyPath}" at line ${index + 1}: expected numeric scalar`,
            );
        }

        const value = Number(rawValue);
        if (!Number.isFinite(value)) {
            throw new Error(`Invalid numeric value for "${keyPath}" at line ${index + 1}`);
        }

        result.set(keyPath, { raw: rawValue, value });
    });

    return result;
}

function validateAgainstSchema(parsed) {
    const schemaKeys = new Set(SCHEMA.map(([pathKey]) => pathKey));
    const parsedKeys = new Set(parsed.keys());

    for (const key of schemaKeys) {
        if (!parsedKeys.has(key)) {
            throw new Error(`Missing key in YAML: "${key}"`);
        }
    }

    for (const key of parsedKeys) {
        if (!schemaKeys.has(key as string)) {
            throw new Error(`Unknown key in YAML: "${key}"`);
        }
    }
}

function buildJsModule(parsed) {
    const lines = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-runtime-params.mjs");
    lines.push("// Source: config/runtime.yaml");
    lines.push("");
    lines.push("export const RUNTIME_PARAMS = Object.freeze({");

    for (const [pathKey, outKey] of SCHEMA) {
        lines.push(`    ${outKey}: ${parsed.get(pathKey).raw},`);
    }

    lines.push("});");
    lines.push("");
    return `${lines.join("\n")}\n`;
}

function ensureParentDir(filePath) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFileIfChanged(filePath, nextContent) {
    const currentContent = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
    if (currentContent === nextContent) {
        return false;
    }
    ensureParentDir(filePath);
    fs.writeFileSync(filePath, nextContent);
    return true;
}

function main() {
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed);

    const jsChanged = writeFileIfChanged(JS_OUT_PATH, buildJsModule(parsed));
    const changedCount = Number(jsChanged);
    console.log(
        `runtime params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${changedCount} file(s) updated)`,
    );
}

main();
