import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    loadSchemaFromJson,
    parseYamlNumericScalars,
    validateAgainstSchema,
    writeFileIfChanged,
    jsLiteral,
    type SchemaEntry,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "runtime.yaml");
const SCHEMA_PATH = path.join(ROOT_DIR, "config", "schema", "runtime.schema.json");
const JS_OUT_PATH = path.join(ROOT_DIR, "web", "src", "interface", "params", "runtime.js");

function buildJsModule(parsed: Map<string, { raw: string; value: number }>, schema: SchemaEntry[]) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-runtime-params.mjs");
    lines.push("// Source: config/runtime.yaml");
    lines.push("");
    lines.push("export const RUNTIME_PARAMS = Object.freeze({");

    for (const [pathKey, outKey] of schema) {
        lines.push(`    ${outKey}: ${jsLiteral(parsed.get(pathKey)!.raw)},`);
    }

    lines.push("});");
    return `${lines.join("\n")}\n`;
}

function main() {
    const schema: SchemaEntry[] = loadSchemaFromJson(SCHEMA_PATH);
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, schema);

    const jsChanged = writeFileIfChanged(JS_OUT_PATH, buildJsModule(parsed, schema));
    const changedCount = Number(jsChanged);
    console.log(
        `runtime params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${changedCount} file(s) updated)`,
    );
}

main();
