import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
    parseYamlNumericScalars,
    rustLiteral,
    type SchemaEntry,
    validateAgainstSchema,
    writeFileIfChanged,
} from "./yaml-sync-helper.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..", "..");
const YAML_PATH = path.join(ROOT_DIR, "config", "glaciology.yaml");
const RUST_OUT_PATH = path.join(
    ROOT_DIR,
    "rust",
    "src",
    "generated",
    "glaciology_params_defaults.rs",
);

const SCHEMA: SchemaEntry[] = [
    ["temperature.accum_temp_threshold_c", "accum_temp_threshold_c", "f32"],
    ["temperature.ablation_temp_threshold_c", "ablation_temp_threshold_c", "f32"],
    ["mass_balance.accumulation_gain", "accumulation_gain", "f32"],
    ["mass_balance.accumulation_temp_sensitivity", "accumulation_temp_sensitivity", "f32"],
    ["mass_balance.ablation_gain", "ablation_gain", "f32"],
    ["mass_balance.thickness_response_rate", "thickness_response_rate", "f32"],
    ["mass_balance.melt_runoff_gain", "melt_runoff_gain", "f32"],
    ["erosion.erosion_gain", "erosion_gain", "f32"],
    ["erosion.glacial_erosion_coupling", "glacial_erosion_coupling", "f32"],
];

function buildRustModule(parsed: Map<string, { raw: string; value: number }>) {
    const lines: string[] = [];
    lines.push("// AUTO-GENERATED by tools/sync/sync-glaciology-params.mjs");
    lines.push("// Source: config/glaciology.yaml");
    lines.push("");
    lines.push("use crate::sim::glaciology::types::GlaciologyParams;");
    lines.push("");
    lines.push("pub(crate) fn build_default_glaciology_params() -> GlaciologyParams {");
    lines.push("    GlaciologyParams {");
    for (const [pathKey, outKey, typeHint] of SCHEMA) {
        const raw = parsed.get(pathKey)!.raw;
        lines.push(`        ${outKey}: ${rustLiteral(raw, typeHint)},`);
    }
    lines.push("    }");
    lines.push("}");
    return `${lines.join("\n")}\n`;
}

function main() {
    const yamlText = fs.readFileSync(YAML_PATH, "utf8");
    const parsed = parseYamlNumericScalars(yamlText);
    validateAgainstSchema(parsed, SCHEMA);

    const changed = writeFileIfChanged(RUST_OUT_PATH, buildRustModule(parsed));
    console.log(
        `glaciology params synced from ${path.relative(ROOT_DIR, YAML_PATH)} (${Number(changed)} file(s) updated)`,
    );
}

main();
